using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Globalization;

namespace EndpointMapper.SourceGenerator;

[Generator]
public class MapMethodsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var endpoints = context.SyntaxProvider
            .CreateSyntaxProvider(predicate: static (node, _) => node is ClassDeclarationSyntax, transform: SyntaxEndpointTransformer)
            .Where(static x => x is not null)
            .Select(static (x, _) => x!)
            .Collect();

        context.RegisterSourceOutput(source: endpoints, action: SourceOutputAction);
        context.RegisterPostInitializationOutput(ctx => ctx.AddEmbeddedAttributeDefinition());
    }

    private static EndpointClassInformation? SyntaxEndpointTransformer(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var nodeSymbol = context.SemanticModel.GetDeclaredSymbol(context.Node, ct) ?? throw new InvalidOperationException("Can't get class declaration symbol");
        var endpointInterface = context.SemanticModel.Compilation.GetTypeByMetadataName("EndpointMapper.IEndpoint") ?? throw new InvalidOperationException("Can't find IEndpoint");
        var httpMapAttribute = context.SemanticModel.Compilation.GetTypeByMetadataName("EndpointMapper.HttpMapAttribute") ?? throw new InvalidOperationException("Can't find HttpMapAttribute");

        // Check that the class implements the IEndpoint interface.
        if (nodeSymbol is not INamedTypeSymbol classSymbol || !classSymbol.Interfaces.Contains(endpointInterface)) return null;

        var endpoints = classSymbol
            .GetMembers()
            .Where(symbol => symbol is { IsStatic: true, Kind: SymbolKind.Method })
            .SelectMany(collectionSelector: symbol =>
                {
                    return symbol
                        .GetAttributes()
                        .Where(attribute => attribute.AttributeClass?.Equals(httpMapAttribute, SymbolEqualityComparer.Default) is true);
                },
                resultSelector: (symbol, attribute) =>
                {
                    if (
                        attribute.ConstructorArguments[0] is not { Kind: TypedConstantKind.Primitive, Value: string httpMethod } ||
                        attribute.ConstructorArguments[1] is not { Kind: TypedConstantKind.Array, Values: var routesArray }
                    )
                    {
                        throw new Exception("Invalid HttpMap attribute");
                    }

                    var routes = routesArray.Select(x => (string)x.Value!).ToImmutableArray();
                    return new EndpointMethodInformation(symbol.Name, httpMethod, routes);
                })
            .ToImmutableArray();

        return new EndpointClassInformation(endpoints, classSymbol.ToDisplayString());
    }

    private static void SourceOutputAction(SourceProductionContext context, ImmutableArray<EndpointClassInformation> endpointClasses)
    {
        using var stringWriter = new StringWriter(CultureInfo.InvariantCulture);
        using var codeWriter = new CodeWriter(stringWriter, baseIndent: 0);

        var assembly = typeof(MapMethodsGenerator).Assembly;
        var name = assembly.FullName;
        var version = assembly.GetName().Version;

        codeWriter.WriteLine("// <auto-generated/>");
        codeWriter.WriteLine("#nullable enable");
        codeWriter.WriteLine();
        codeWriter.WriteLine("namespace EndpointMapper");
        codeWriter.StartBlock();
        codeWriter.WriteLine($"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{name}", "{version}")]""");
        codeWriter.WriteLine("[global::Microsoft.CodeAnalysis.EmbeddedAttribute]");
        codeWriter.WriteLine("internal static class EndpointMapperExtensions");
        codeWriter.StartBlock();

        // Helper methods to call the virtual methods on IEndpoint
        codeWriter.WriteLine("private static void Register<T>(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder) where T : global::EndpointMapper.IEndpoint => T.Register(builder);");
        codeWriter.WriteLine("private static void Configure<T>(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder, string route, string method) where T : global::EndpointMapper.IEndpoint => T.Configure(builder, route, method);");

        codeWriter.WriteLine("public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapEndpointMapperEndpoints(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)");
        codeWriter.StartBlock();

        foreach (var (endpoints, className) in endpointClasses)
        {
            codeWriter.WriteLine($"// Mapping endpoints in {className}");
            codeWriter.WriteLine($"Register<global::{className}>(builder);");
            foreach (var methodInformation in endpoints) MapRoutes(codeWriter, methodInformation, className);

            codeWriter.WriteLine();
        }

        codeWriter.WriteLine("return builder;");
        codeWriter.EndBlock(); // End of MapEndpointMapperEndpoints
        codeWriter.EndBlock(); // End of EndpointMapperExtensions
        codeWriter.EndBlock(); // End of namespace EndpointMapper

        context.AddSource("Endpoints.g.cs", stringWriter.ToString());
    }

    private static void MapRoutes(CodeWriter codeWriter, EndpointMethodInformation methodInformation, string containingType)
    {
        foreach (var route in methodInformation.Routes)
        {
            // Get, Post, Put, Delete, Patch have a built-in method so we use those, for the other methods we need to use MapMethods.
            var builderMethod = methodInformation.HttpVerb switch
            {
                "GET" => $"""MapGet(builder, "{route}",""",
                "POST" => $"""MapPost(builder, "{route}",""",
                "PUT" => $"""MapPut(builder, "{route}",""",
                "DELETE" => $"""MapDelete(builder, "{route}",""",
                "PATCH" => $"""MapPatch(builder, "{route}",""",
                var method => $"""MapMethods(builder, "{route}", ["{method}"],""",
            };

            codeWriter.WriteLine($"""Configure<global::{containingType}>(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.{builderMethod} global::{containingType}.{methodInformation.MethodName}), "{route}", "{methodInformation.HttpVerb}");""");
        }
    }
}
