<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <UserSecretsId>4a48b8ee-702c-49d0-a843-75aba2d9fd87</UserSecretsId>
        <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EndpointMapper\EndpointMapper.csproj" />
        <ProjectReference Include="..\EndpointMapper.SourceGenerator\EndpointMapper.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" PrivateAssets="all" />
    </ItemGroup>
</Project>
