<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>

    <UseLocalProjects>true</UseLocalProjects>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseLocalProjects)' == 'true'">
    <ProjectReference Include="..\EndpointMapper\EndpointMapper.csproj"  />
    <ProjectReference Include="..\EndpointMapper.SourceGenerator\EndpointMapper.SourceGenerator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="true"
      PrivateAssets="all" />
    </ItemGroup>

  <ItemGroup Condition="'$(UseLocalProjects)' == 'false'">
    <!-- This requires to setup a nuget source in the artifacts/package/<Configuration> or else it will use Nuget -->
    <PackageReference Include="EndpointMapper" Version="$(Version)" />
  </ItemGroup>

</Project>
