name: .NET Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish EndpointMapper --no-restore --property:ContinuousIntegrationBuild=true
    - name: Get the release tag
      id: get_release_tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: Upload artifact to the Github Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release upload ${{ steps.get_release_tag.outputs.tag }} artifacts/package/release/* --clobber
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
    - name: NuGet push
      run: dotnet nuget push artifacts/package/release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
